theme: minima
title: orange-lee-tech's Homepage
author: 李雨橙
description: 欢迎来到李雨橙的个人主页，这里有丰富的信息，关于他公开的完整履历信息、兴趣爱好、行业、规划，博主期望读者能够与他建立联系。

page-top-title: Yourname
top-section-bg-text: Marching Forward 
home-subtitle: 李雨橙&ensp;|&雨涟帘;orange-lee-tech
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
