title: orange-lee-tech's Homepage
page-top-title: Yourname
top-section-bg-text: Marching Forward 
home-subtitle: 李雨橙&ensp;|&雨涟帘;orange-lee-tech
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
show-images:
  - image1.jpg
  - image2.jpg
  - image3.jpg
  - image4.jpg
  - image5.jpg
  - image6.jpg
  - image7.jpg
  - image8.jpg
person-images:
  - image9.jpg
  - image10.jpg
  - image11.jpg
  - image12.jpg
  - image13.jpg
  - image14.jpg
